language: java

script:
    - mvn clean -q verify

deploy:
  provider: heroku
  api_key:
    secure: 58c0d6f0-6d86-4b15-bb6e-c6d28751fdbc
  app: clientd
  on:
    all_branches: true
  run:
    - java -jar target/clientD-1.0.jar
