language: java

script:
    - mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: 58c0d6f0-6d86-4b15-bb6e-c6d28751fdbc
  app: clientd
  on:
    all_branches: true
  run:
    - mvn deploy && java -jar deployDir/com/practice/clientD/1.0-SNAPSHOT/*-with-dependencies.jar
